apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sysdig-deploy
spec:
  destination:
    name: ''
    namespace: sysdig-agent
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
  - name: sysdig-clustershield
    kind: Secret
    jsonPointers:
    - /data/sysdig-cluster-nats-password
  - name: sysdig-clustershield-tls-certs
    kind: Secret
    jsonPointers:
    - /data
  - name: sysdig-deploy-clustershield-audit
    kind: ValidatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[] | select(.name | test("\\.secure\\.sysdig\\.com")).clientConfig.caBundle
  sources:
  - repoURL: 'https://charts.sysdig.com'
    chart: sysdig-deploy
    targetRevision: 1.67.6
    helm:
      valueFiles:
      - $values/common/sysdig-deploy-common-clustershield-values.yaml
      - $values/nonprod/sysdig-deploy-labeks.yaml
  - repoURL: 'https://github.com/shawnjohnson/argocd-sysdig-example.git'
    targetRevision: main
    ref: values
  project: default
  syncPolicy:
    automated: 
      prune: true
      #selfHeal: true
    syncOptions:
      - CreateNamespace=true
